### ISSUE TITLE
Review sections of methods, discussion

### ISSUE THREAD

**Issue by staylorofford** [staylorofford/publications#58]

**Comment by staylorofford** [comment]
@horganhu I would like to assign you to this

**Comment by horganhu** [comment]
Hey Sam,

I’ve had a good go at the methods sections but need to go through the Discussion. Haven’t looked at the letter yet.

I’ll be on this tomorrow as well.

I’ve been in touch with Paul and sent him the revised (but not quite finished) draft to get his nod of approval.

Cheers - Huw


On 12/02/2019, at 8:18 pm, Sam Taylor-Offord <notifications@github.com<mailto:notifications@github.com>> wrote:


@horganhu<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhorganhu&data=02%7C01%7Chuw.horgan%40vuw.ac.nz%7Ccd9117808b074288bb9e08d690ba4c2f%7Ccfe63e236951427e8683bb84dcf1d20c%7C0%7C0%7C636855527204638319&sdata=HkbrqA%2FcCjpmmKxXy9t97I0NbgAKfde3%2FtrKFpqqdoA%3D&reserved=0> I would like to assign you to this
